/* tslint:disable */
/* eslint-disable */
/**
 * brokerize
 * The brokerize API allows clients to implement multi-brokerage with a unified interface. For more information, visit brokerize.com
 *
 * The version of the OpenAPI document: 0.0.1-preview
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import {
  Challenge,
  ChallengeFromJSON,
  ChallengeToJSON,
  ChangeOrderChallengeParams,
  ChangeOrderChallengeParamsFromJSON,
  ChangeOrderChallengeParamsToJSON,
  ChangeOrderParams,
  ChangeOrderParamsFromJSON,
  ChangeOrderParamsToJSON,
  ErrorResponse,
  ErrorResponseFromJSON,
  ErrorResponseToJSON,
  EstimateChangeOrderCostsParams,
  EstimateChangeOrderCostsParamsFromJSON,
  EstimateChangeOrderCostsParamsToJSON,
  OrderCostEstimation,
  OrderCostEstimationFromJSON,
  OrderCostEstimationToJSON,
} from "../models";

export interface ChangeOrderRequest {
  id: string;
  changeOrderParams: ChangeOrderParams;
}

export interface CreateChangeOrderChallengeRequest {
  id: string;
  changeOrderChallengeParams: ChangeOrderChallengeParams;
}

export interface GetChangeOrderCostEstimationRequest {
  id: string;
  estimateChangeOrderCostsParams: EstimateChangeOrderCostsParams;
}

/**
 *
 */
export class ChangeOrderApi extends runtime.BaseAPI {
  /**
   * Perform an order change.
   */
  async changeOrderRaw(
    requestParameters: ChangeOrderRequest,
    initOverrides?: RequestInit | runtime.InitOverideFunction
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        "id",
        "Required parameter requestParameters.id was null or undefined when calling changeOrder."
      );
    }

    if (
      requestParameters.changeOrderParams === null ||
      requestParameters.changeOrderParams === undefined
    ) {
      throw new runtime.RequiredError(
        "changeOrderParams",
        "Required parameter requestParameters.changeOrderParams was null or undefined when calling changeOrder."
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["x-brkrz-client-id"] =
        this.configuration.apiKey("x-brkrz-client-id"); // clientId authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["x-access-token"] =
        this.configuration.apiKey("x-access-token"); // idToken authentication
    }

    const response = await this.request(
      {
        path: `/order/{id}/change`.replace(
          `{${"id"}}`,
          encodeURIComponent(String(requestParameters.id))
        ),
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: ChangeOrderParamsToJSON(requestParameters.changeOrderParams),
      },
      initOverrides
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Perform an order change.
   */
  async changeOrder(
    requestParameters: ChangeOrderRequest,
    initOverrides?: RequestInit | runtime.InitOverideFunction
  ): Promise<void> {
    await this.changeOrderRaw(requestParameters, initOverrides);
  }

  /**
   * If the user chose an auth method from `GetAuthInfo` with the flow `CHALLENGE_RESPONSE`, before changing an order, a challenge must be requested first. If any other flow is used, a challenge *must not* be requested and `ChangeOrder` is used right away.
   */
  async createChangeOrderChallengeRaw(
    requestParameters: CreateChangeOrderChallengeRequest,
    initOverrides?: RequestInit | runtime.InitOverideFunction
  ): Promise<runtime.ApiResponse<Challenge>> {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        "id",
        "Required parameter requestParameters.id was null or undefined when calling createChangeOrderChallenge."
      );
    }

    if (
      requestParameters.changeOrderChallengeParams === null ||
      requestParameters.changeOrderChallengeParams === undefined
    ) {
      throw new runtime.RequiredError(
        "changeOrderChallengeParams",
        "Required parameter requestParameters.changeOrderChallengeParams was null or undefined when calling createChangeOrderChallenge."
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["x-brkrz-client-id"] =
        this.configuration.apiKey("x-brkrz-client-id"); // clientId authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["x-access-token"] =
        this.configuration.apiKey("x-access-token"); // idToken authentication
    }

    const response = await this.request(
      {
        path: `/order/{id}/changeChallenge`.replace(
          `{${"id"}}`,
          encodeURIComponent(String(requestParameters.id))
        ),
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: ChangeOrderChallengeParamsToJSON(
          requestParameters.changeOrderChallengeParams
        ),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ChallengeFromJSON(jsonValue)
    );
  }

  /**
   * If the user chose an auth method from `GetAuthInfo` with the flow `CHALLENGE_RESPONSE`, before changing an order, a challenge must be requested first. If any other flow is used, a challenge *must not* be requested and `ChangeOrder` is used right away.
   */
  async createChangeOrderChallenge(
    requestParameters: CreateChangeOrderChallengeRequest,
    initOverrides?: RequestInit | runtime.InitOverideFunction
  ): Promise<Challenge> {
    const response = await this.createChangeOrderChallengeRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * Get an order cost estimation for an order change.
   */
  async getChangeOrderCostEstimationRaw(
    requestParameters: GetChangeOrderCostEstimationRequest,
    initOverrides?: RequestInit | runtime.InitOverideFunction
  ): Promise<runtime.ApiResponse<OrderCostEstimation>> {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        "id",
        "Required parameter requestParameters.id was null or undefined when calling getChangeOrderCostEstimation."
      );
    }

    if (
      requestParameters.estimateChangeOrderCostsParams === null ||
      requestParameters.estimateChangeOrderCostsParams === undefined
    ) {
      throw new runtime.RequiredError(
        "estimateChangeOrderCostsParams",
        "Required parameter requestParameters.estimateChangeOrderCostsParams was null or undefined when calling getChangeOrderCostEstimation."
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["x-brkrz-client-id"] =
        this.configuration.apiKey("x-brkrz-client-id"); // clientId authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["x-access-token"] =
        this.configuration.apiKey("x-access-token"); // idToken authentication
    }

    const response = await this.request(
      {
        path: `/order/{id}/changeCostEstimation`.replace(
          `{${"id"}}`,
          encodeURIComponent(String(requestParameters.id))
        ),
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: EstimateChangeOrderCostsParamsToJSON(
          requestParameters.estimateChangeOrderCostsParams
        ),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      OrderCostEstimationFromJSON(jsonValue)
    );
  }

  /**
   * Get an order cost estimation for an order change.
   */
  async getChangeOrderCostEstimation(
    requestParameters: GetChangeOrderCostEstimationRequest,
    initOverrides?: RequestInit | runtime.InitOverideFunction
  ): Promise<OrderCostEstimation> {
    const response = await this.getChangeOrderCostEstimationRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }
}
