/* tslint:disable */
/* eslint-disable */
/**
 * brokerize
 * The brokerize API allows clients to implement multi-brokerage with a unified interface. For more information, visit brokerize.com
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import {
  CancelOrderChallengeParams,
  CancelOrderChallengeParamsFromJSON,
  CancelOrderChallengeParamsToJSON,
  CancelOrderParams,
  CancelOrderParamsFromJSON,
  CancelOrderParamsToJSON,
  CancelOrderResponse,
  CancelOrderResponseFromJSON,
  CancelOrderResponseToJSON,
  Challenge,
  ChallengeFromJSON,
  ChallengeToJSON,
  ChangeOrderChallengeParams,
  ChangeOrderChallengeParamsFromJSON,
  ChangeOrderChallengeParamsToJSON,
  ChangeOrderParams,
  ChangeOrderParamsFromJSON,
  ChangeOrderParamsToJSON,
  ChangeOrderResponse,
  ChangeOrderResponseFromJSON,
  ChangeOrderResponseToJSON,
  ErrorResponse,
  ErrorResponseFromJSON,
  ErrorResponseToJSON,
  EstimateChangeOrderCostsParams,
  EstimateChangeOrderCostsParamsFromJSON,
  EstimateChangeOrderCostsParamsToJSON,
  GetOrderResponse,
  GetOrderResponseFromJSON,
  GetOrderResponseToJSON,
  OrderCostEstimation,
  OrderCostEstimationFromJSON,
  OrderCostEstimationToJSON,
} from "../models";

export interface CancelOrderRequest {
  id: string;
  cancelOrderParams: CancelOrderParams;
}

export interface ChangeOrderRequest {
  id: string;
  changeOrderParams: ChangeOrderParams;
}

export interface CreateCancelOrderChallengeRequest {
  id: string;
  cancelOrderChallengeParams: CancelOrderChallengeParams;
}

export interface CreateChangeOrderChallengeRequest {
  id: string;
  changeOrderChallengeParams: ChangeOrderChallengeParams;
}

export interface GetChangeOrderCostEstimationRequest {
  id: string;
  estimateChangeOrderCostsParams: EstimateChangeOrderCostsParams;
}

export interface GetOrderRequest {
  id: string;
}

/**
 *
 */
export class OrderApi extends runtime.BaseAPI {
  /**
   * Cancel the given order (or in the case of decoupled authMethods: send the order cancellation to the user for confirmation. In this case, a decoupledOperationId is returned).
   */
  async cancelOrderRaw(
    requestParameters: CancelOrderRequest,
    initOverrides?: RequestInit | runtime.InitOverideFunction
  ): Promise<runtime.ApiResponse<CancelOrderResponse>> {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        "id",
        "Required parameter requestParameters.id was null or undefined when calling cancelOrder."
      );
    }

    if (
      requestParameters.cancelOrderParams === null ||
      requestParameters.cancelOrderParams === undefined
    ) {
      throw new runtime.RequiredError(
        "cancelOrderParams",
        "Required parameter requestParameters.cancelOrderParams was null or undefined when calling cancelOrder."
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["x-brkrz-client-id"] =
        this.configuration.apiKey("x-brkrz-client-id"); // clientId authentication
    }

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("idToken", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/order/{id}/cancel`.replace(
          `{${"id"}}`,
          encodeURIComponent(String(requestParameters.id))
        ),
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: CancelOrderParamsToJSON(requestParameters.cancelOrderParams),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      CancelOrderResponseFromJSON(jsonValue)
    );
  }

  /**
   * Cancel the given order (or in the case of decoupled authMethods: send the order cancellation to the user for confirmation. In this case, a decoupledOperationId is returned).
   */
  async cancelOrder(
    requestParameters: CancelOrderRequest,
    initOverrides?: RequestInit | runtime.InitOverideFunction
  ): Promise<CancelOrderResponse> {
    const response = await this.cancelOrderRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * Perform an order change.
   */
  async changeOrderRaw(
    requestParameters: ChangeOrderRequest,
    initOverrides?: RequestInit | runtime.InitOverideFunction
  ): Promise<runtime.ApiResponse<ChangeOrderResponse>> {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        "id",
        "Required parameter requestParameters.id was null or undefined when calling changeOrder."
      );
    }

    if (
      requestParameters.changeOrderParams === null ||
      requestParameters.changeOrderParams === undefined
    ) {
      throw new runtime.RequiredError(
        "changeOrderParams",
        "Required parameter requestParameters.changeOrderParams was null or undefined when calling changeOrder."
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["x-brkrz-client-id"] =
        this.configuration.apiKey("x-brkrz-client-id"); // clientId authentication
    }

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("idToken", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/order/{id}/change`.replace(
          `{${"id"}}`,
          encodeURIComponent(String(requestParameters.id))
        ),
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: ChangeOrderParamsToJSON(requestParameters.changeOrderParams),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ChangeOrderResponseFromJSON(jsonValue)
    );
  }

  /**
   * Perform an order change.
   */
  async changeOrder(
    requestParameters: ChangeOrderRequest,
    initOverrides?: RequestInit | runtime.InitOverideFunction
  ): Promise<ChangeOrderResponse> {
    const response = await this.changeOrderRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * If the user chose an auth method from `GetAuthInfo` with the flow `CHALLENGE_RESPONSE`, before cancelling an order, a challenge must be requested first. If any other flow is used, a challenge *must not* be requested and `CancelOrder` is used right away.
   */
  async createCancelOrderChallengeRaw(
    requestParameters: CreateCancelOrderChallengeRequest,
    initOverrides?: RequestInit | runtime.InitOverideFunction
  ): Promise<runtime.ApiResponse<Challenge>> {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        "id",
        "Required parameter requestParameters.id was null or undefined when calling createCancelOrderChallenge."
      );
    }

    if (
      requestParameters.cancelOrderChallengeParams === null ||
      requestParameters.cancelOrderChallengeParams === undefined
    ) {
      throw new runtime.RequiredError(
        "cancelOrderChallengeParams",
        "Required parameter requestParameters.cancelOrderChallengeParams was null or undefined when calling createCancelOrderChallenge."
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["x-brkrz-client-id"] =
        this.configuration.apiKey("x-brkrz-client-id"); // clientId authentication
    }

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("idToken", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/order/{id}/cancelChallenge`.replace(
          `{${"id"}}`,
          encodeURIComponent(String(requestParameters.id))
        ),
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: CancelOrderChallengeParamsToJSON(
          requestParameters.cancelOrderChallengeParams
        ),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ChallengeFromJSON(jsonValue)
    );
  }

  /**
   * If the user chose an auth method from `GetAuthInfo` with the flow `CHALLENGE_RESPONSE`, before cancelling an order, a challenge must be requested first. If any other flow is used, a challenge *must not* be requested and `CancelOrder` is used right away.
   */
  async createCancelOrderChallenge(
    requestParameters: CreateCancelOrderChallengeRequest,
    initOverrides?: RequestInit | runtime.InitOverideFunction
  ): Promise<Challenge> {
    const response = await this.createCancelOrderChallengeRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * If the user chose an auth method from `GetAuthInfo` with the flow `CHALLENGE_RESPONSE`, before changing an order, a challenge must be requested first. If any other flow is used, a challenge *must not* be requested and `ChangeOrder` is used right away.
   */
  async createChangeOrderChallengeRaw(
    requestParameters: CreateChangeOrderChallengeRequest,
    initOverrides?: RequestInit | runtime.InitOverideFunction
  ): Promise<runtime.ApiResponse<Challenge>> {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        "id",
        "Required parameter requestParameters.id was null or undefined when calling createChangeOrderChallenge."
      );
    }

    if (
      requestParameters.changeOrderChallengeParams === null ||
      requestParameters.changeOrderChallengeParams === undefined
    ) {
      throw new runtime.RequiredError(
        "changeOrderChallengeParams",
        "Required parameter requestParameters.changeOrderChallengeParams was null or undefined when calling createChangeOrderChallenge."
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["x-brkrz-client-id"] =
        this.configuration.apiKey("x-brkrz-client-id"); // clientId authentication
    }

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("idToken", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/order/{id}/changeChallenge`.replace(
          `{${"id"}}`,
          encodeURIComponent(String(requestParameters.id))
        ),
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: ChangeOrderChallengeParamsToJSON(
          requestParameters.changeOrderChallengeParams
        ),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ChallengeFromJSON(jsonValue)
    );
  }

  /**
   * If the user chose an auth method from `GetAuthInfo` with the flow `CHALLENGE_RESPONSE`, before changing an order, a challenge must be requested first. If any other flow is used, a challenge *must not* be requested and `ChangeOrder` is used right away.
   */
  async createChangeOrderChallenge(
    requestParameters: CreateChangeOrderChallengeRequest,
    initOverrides?: RequestInit | runtime.InitOverideFunction
  ): Promise<Challenge> {
    const response = await this.createChangeOrderChallengeRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * Get an order cost estimation for an order change.
   */
  async getChangeOrderCostEstimationRaw(
    requestParameters: GetChangeOrderCostEstimationRequest,
    initOverrides?: RequestInit | runtime.InitOverideFunction
  ): Promise<runtime.ApiResponse<OrderCostEstimation>> {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        "id",
        "Required parameter requestParameters.id was null or undefined when calling getChangeOrderCostEstimation."
      );
    }

    if (
      requestParameters.estimateChangeOrderCostsParams === null ||
      requestParameters.estimateChangeOrderCostsParams === undefined
    ) {
      throw new runtime.RequiredError(
        "estimateChangeOrderCostsParams",
        "Required parameter requestParameters.estimateChangeOrderCostsParams was null or undefined when calling getChangeOrderCostEstimation."
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["x-brkrz-client-id"] =
        this.configuration.apiKey("x-brkrz-client-id"); // clientId authentication
    }

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("idToken", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/order/{id}/changeCostEstimation`.replace(
          `{${"id"}}`,
          encodeURIComponent(String(requestParameters.id))
        ),
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: EstimateChangeOrderCostsParamsToJSON(
          requestParameters.estimateChangeOrderCostsParams
        ),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      OrderCostEstimationFromJSON(jsonValue)
    );
  }

  /**
   * Get an order cost estimation for an order change.
   */
  async getChangeOrderCostEstimation(
    requestParameters: GetChangeOrderCostEstimationRequest,
    initOverrides?: RequestInit | runtime.InitOverideFunction
  ): Promise<OrderCostEstimation> {
    const response = await this.getChangeOrderCostEstimationRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   */
  async getOrderRaw(
    requestParameters: GetOrderRequest,
    initOverrides?: RequestInit | runtime.InitOverideFunction
  ): Promise<runtime.ApiResponse<GetOrderResponse>> {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        "id",
        "Required parameter requestParameters.id was null or undefined when calling getOrder."
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["x-brkrz-client-id"] =
        this.configuration.apiKey("x-brkrz-client-id"); // clientId authentication
    }

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("idToken", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/order/{id}`.replace(
          `{${"id"}}`,
          encodeURIComponent(String(requestParameters.id))
        ),
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      GetOrderResponseFromJSON(jsonValue)
    );
  }

  /**
   */
  async getOrder(
    requestParameters: GetOrderRequest,
    initOverrides?: RequestInit | runtime.InitOverideFunction
  ): Promise<GetOrderResponse> {
    const response = await this.getOrderRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
