/* tslint:disable */
/* eslint-disable */
/**
 * brokerize
 * The brokerize API allows clients to implement multi-brokerage with a unified interface. For more information, visit brokerize.com
 *
 * The version of the OpenAPI document: 1.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AuthMethodDecoupledSpecifics
 */
export interface AuthMethodDecoupledSpecifics {
  /**
   * If this is true, the auth method should not be offered to users on phones (e.g. for photoTAN, where the TAN has to
   * be scanned with a phone).
   * @type {boolean}
   * @memberof AuthMethodDecoupledSpecifics
   */
  hideOnPhones?: boolean;
  /**
   *
   * @type {string}
   * @memberof AuthMethodDecoupledSpecifics
   */
  id?: string;
  /**
   *
   * @type {boolean}
   * @memberof AuthMethodDecoupledSpecifics
   */
  isDefaultMethod?: boolean;
  /**
   *
   * @type {string}
   * @memberof AuthMethodDecoupledSpecifics
   */
  label?: string;
}

export function AuthMethodDecoupledSpecificsFromJSON(
  json: any
): AuthMethodDecoupledSpecifics {
  return AuthMethodDecoupledSpecificsFromJSONTyped(json, false);
}

export function AuthMethodDecoupledSpecificsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AuthMethodDecoupledSpecifics {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    hideOnPhones: !exists(json, "hideOnPhones")
      ? undefined
      : json["hideOnPhones"],
    id: !exists(json, "id") ? undefined : json["id"],
    isDefaultMethod: !exists(json, "isDefaultMethod")
      ? undefined
      : json["isDefaultMethod"],
    label: !exists(json, "label") ? undefined : json["label"],
  };
}

export function AuthMethodDecoupledSpecificsToJSONRecursive(
  value?: AuthMethodDecoupledSpecifics | null,
  ignoreParent = false
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }

  return {
    hideOnPhones: value.hideOnPhones,
    id: value.id,
    isDefaultMethod: value.isDefaultMethod,
    label: value.label,
  };
}

export function AuthMethodDecoupledSpecificsToJSON(
  value?: AuthMethodDecoupledSpecifics | null
): any {
  return AuthMethodDecoupledSpecificsToJSONRecursive(value, false);
}
