/* tslint:disable */
/* eslint-disable */
/**
 * brokerize
 * The brokerize API allows clients to implement multi-brokerage with a unified interface. For more information, visit brokerize.com
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ChangeOrderResponse
 */
export interface ChangeOrderResponse {
  /**
   * If a decoupled method is used to change the order, the cancellation process can be observed through the
   * `decoupledOperationId`.
   * @type {string}
   * @memberof ChangeOrderResponse
   */
  decoupledOperationId?: string;
}

export function ChangeOrderResponseFromJSON(json: any): ChangeOrderResponse {
  return ChangeOrderResponseFromJSONTyped(json, false);
}

export function ChangeOrderResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChangeOrderResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    decoupledOperationId: !exists(json, "decoupledOperationId")
      ? undefined
      : json["decoupledOperationId"],
  };
}

export function ChangeOrderResponseToJSONRecursive(
  value?: ChangeOrderResponse | null,
  ignoreParent = false
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }

  return {
    decoupledOperationId: value.decoupledOperationId,
  };
}

export function ChangeOrderResponseToJSON(
  value?: ChangeOrderResponse | null
): any {
  return ChangeOrderResponseToJSONRecursive(value, false);
}
