/* tslint:disable */
/* eslint-disable */
/**
 * brokerize
 * The brokerize API allows clients to implement multi-brokerage with a unified interface. For more information, visit brokerize.com
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CheckRecoveryPhrase200Response
 */
export interface CheckRecoveryPhrase200Response {
  /**
   *
   * @type {Date}
   * @memberof CheckRecoveryPhrase200Response
   */
  expiresAt: Date;
}

export function CheckRecoveryPhrase200ResponseFromJSON(
  json: any
): CheckRecoveryPhrase200Response {
  return CheckRecoveryPhrase200ResponseFromJSONTyped(json, false);
}

export function CheckRecoveryPhrase200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CheckRecoveryPhrase200Response {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    expiresAt: new Date(json["expiresAt"]),
  };
}

export function CheckRecoveryPhrase200ResponseToJSONRecursive(
  value?: CheckRecoveryPhrase200Response | null,
  ignoreParent = false
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }

  return {
    expiresAt: value.expiresAt.toISOString(),
  };
}

export function CheckRecoveryPhrase200ResponseToJSON(
  value?: CheckRecoveryPhrase200Response | null
): any {
  return CheckRecoveryPhrase200ResponseToJSONRecursive(value, false);
}
