/* tslint:disable */
/* eslint-disable */
/**
 * brokerize
 * The brokerize API allows clients to implement multi-brokerage with a unified interface. For more information, visit brokerize.com
 *
 * The version of the OpenAPI document: 1.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import {
  MaintenanceStatus,
  MaintenanceStatusFromJSON,
  MaintenanceStatusFromJSONTyped,
  MaintenanceStatusToJSON,
} from "./MaintenanceStatus";

/**
 *
 * @export
 * @interface ClientConfigMaintenanceStatus
 */
export interface ClientConfigMaintenanceStatus {
  /**
   *
   * @type {Date}
   * @memberof ClientConfigMaintenanceStatus
   */
  expectedEnd?: Date;
  /**
   *
   * @type {string}
   * @memberof ClientConfigMaintenanceStatus
   */
  msg: string;
}

export function ClientConfigMaintenanceStatusFromJSON(
  json: any
): ClientConfigMaintenanceStatus {
  return ClientConfigMaintenanceStatusFromJSONTyped(json, false);
}

export function ClientConfigMaintenanceStatusFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ClientConfigMaintenanceStatus {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    expectedEnd: !exists(json, "expectedEnd")
      ? undefined
      : new Date(json["expectedEnd"]),
    msg: json["msg"],
  };
}

export function ClientConfigMaintenanceStatusToJSONRecursive(
  value?: ClientConfigMaintenanceStatus | null,
  ignoreParent = false
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }

  return {
    expectedEnd:
      value.expectedEnd === undefined
        ? undefined
        : value.expectedEnd.toISOString(),
    msg: value.msg,
  };
}

export function ClientConfigMaintenanceStatusToJSON(
  value?: ClientConfigMaintenanceStatus | null
): any {
  return ClientConfigMaintenanceStatusToJSONRecursive(value, false);
}
