/* tslint:disable */
/* eslint-disable */
/**
 * brokerize
 * The brokerize API allows clients to implement multi-brokerage with a unified interface. For more information, visit brokerize.com
 *
 * The version of the OpenAPI document: 0.0.1-preview
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ClientConfigUpdateRateLimitPointsToConsume
 */
export interface ClientConfigUpdateRateLimitPointsToConsume {
  /**
   *
   * @type {number}
   * @memberof ClientConfigUpdateRateLimitPointsToConsume
   */
  guestUser?: number;
}

export function ClientConfigUpdateRateLimitPointsToConsumeFromJSON(
  json: any
): ClientConfigUpdateRateLimitPointsToConsume {
  return ClientConfigUpdateRateLimitPointsToConsumeFromJSONTyped(json, false);
}

export function ClientConfigUpdateRateLimitPointsToConsumeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ClientConfigUpdateRateLimitPointsToConsume {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    guestUser: !exists(json, "guestUser") ? undefined : json["guestUser"],
  };
}

export function ClientConfigUpdateRateLimitPointsToConsumeToJSONRecursive(
  value?: ClientConfigUpdateRateLimitPointsToConsume | null,
  ignoreParent = false
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }

  return {
    guestUser: value.guestUser,
  };
}

export function ClientConfigUpdateRateLimitPointsToConsumeToJSON(
  value?: ClientConfigUpdateRateLimitPointsToConsume | null
): any {
  return ClientConfigUpdateRateLimitPointsToConsumeToJSONRecursive(
    value,
    false
  );
}
