/* tslint:disable */
/* eslint-disable */
/**
 * brokerize
 * The brokerize API allows clients to implement multi-brokerage with a unified interface. For more information, visit brokerize.com
 *
 * The version of the OpenAPI document: 0.0.1-preview
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import {
  BrokerEnvFilterType,
  BrokerEnvFilterTypeFromJSON,
  BrokerEnvFilterTypeFromJSONTyped,
  BrokerEnvFilterTypeToJSON,
} from "./BrokerEnvFilterType";
import {
  ClientConfigMaintenanceStatus,
  ClientConfigMaintenanceStatusFromJSON,
  ClientConfigMaintenanceStatusFromJSONTyped,
  ClientConfigMaintenanceStatusToJSON,
} from "./ClientConfigMaintenanceStatus";
import {
  OAuthLoginFormConfig,
  OAuthLoginFormConfigFromJSON,
  OAuthLoginFormConfigFromJSONTyped,
  OAuthLoginFormConfigToJSON,
} from "./OAuthLoginFormConfig";

/**
 *
 * @export
 * @interface ClientsResponseInnerConfig
 */
export interface ClientsResponseInnerConfig {
  /**
   *
   * @type {boolean}
   * @memberof ClientsResponseInnerConfig
   */
  allowRequestsWithoutOrigin: boolean;
  /**
   *
   * @type {Array<string>}
   * @memberof ClientsResponseInnerConfig
   */
  allowedOrigins: Array<string>;
  /**
   *
   * @type {{ [key: string]: BrokerEnvFilterType; }}
   * @memberof ClientsResponseInnerConfig
   */
  brokerEnvFilter: { [key: string]: BrokerEnvFilterType };
  /**
   *
   * @type {Array<string>}
   * @memberof ClientsResponseInnerConfig
   */
  cognitoClientIds: Array<string>;
  /**
   *
   * @type {boolean}
   * @memberof ClientsResponseInnerConfig
   */
  enabled: boolean;
  /**
   *
   * @type {string}
   * @memberof ClientsResponseInnerConfig
   */
  legalEntityName: string;
  /**
   *
   * @type {ClientConfigMaintenanceStatus}
   * @memberof ClientsResponseInnerConfig
   */
  maintenanceStatus: ClientConfigMaintenanceStatus | null;
  /**
   *
   * @type {string}
   * @memberof ClientsResponseInnerConfig
   */
  name: string;
  /**
   *
   * @type {OAuthLoginFormConfig}
   * @memberof ClientsResponseInnerConfig
   */
  oAuthLoginForm?: OAuthLoginFormConfig;
  /**
   *
   * @type {Array<string>}
   * @memberof ClientsResponseInnerConfig
   */
  oAuthReturnToRegularExpressions: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof ClientsResponseInnerConfig
   */
  oAuthReturnToUrls: Array<string>;
  /**
   *
   * @type {any}
   * @memberof ClientsResponseInnerConfig
   */
  page: any | null;
}

export function ClientsResponseInnerConfigFromJSON(
  json: any
): ClientsResponseInnerConfig {
  return ClientsResponseInnerConfigFromJSONTyped(json, false);
}

export function ClientsResponseInnerConfigFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ClientsResponseInnerConfig {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    allowRequestsWithoutOrigin: json["allowRequestsWithoutOrigin"],
    allowedOrigins: json["allowedOrigins"],
    brokerEnvFilter: mapValues(
      json["brokerEnvFilter"],
      BrokerEnvFilterTypeFromJSON
    ),
    cognitoClientIds: json["cognitoClientIds"],
    enabled: json["enabled"],
    legalEntityName: json["legalEntityName"],
    maintenanceStatus: ClientConfigMaintenanceStatusFromJSON(
      json["maintenanceStatus"]
    ),
    name: json["name"],
    oAuthLoginForm: !exists(json, "oAuthLoginForm")
      ? undefined
      : OAuthLoginFormConfigFromJSON(json["oAuthLoginForm"]),
    oAuthReturnToRegularExpressions: json["oAuthReturnToRegularExpressions"],
    oAuthReturnToUrls: json["oAuthReturnToUrls"],
    page: json["page"],
  };
}

export function ClientsResponseInnerConfigToJSONRecursive(
  value?: ClientsResponseInnerConfig | null,
  ignoreParent = false
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }

  return {
    allowRequestsWithoutOrigin: value.allowRequestsWithoutOrigin,
    allowedOrigins: value.allowedOrigins,
    brokerEnvFilter: mapValues(
      value.brokerEnvFilter,
      BrokerEnvFilterTypeToJSON
    ),
    cognitoClientIds: value.cognitoClientIds,
    enabled: value.enabled,
    legalEntityName: value.legalEntityName,
    maintenanceStatus: ClientConfigMaintenanceStatusToJSON(
      value.maintenanceStatus
    ),
    name: value.name,
    oAuthLoginForm: OAuthLoginFormConfigToJSON(value.oAuthLoginForm),
    oAuthReturnToRegularExpressions: value.oAuthReturnToRegularExpressions,
    oAuthReturnToUrls: value.oAuthReturnToUrls,
    page: value.page,
  };
}

export function ClientsResponseInnerConfigToJSON(
  value?: ClientsResponseInnerConfig | null
): any {
  return ClientsResponseInnerConfigToJSONRecursive(value, false);
}
