/* tslint:disable */
/* eslint-disable */
/**
 * brokerize
 * The brokerize API allows clients to implement multi-brokerage with a unified interface. For more information, visit brokerize.com
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CoinbaseClientCfg
 */
export interface CoinbaseClientCfg {
  /**
   *
   * @type {string}
   * @memberof CoinbaseClientCfg
   */
  trackingPrefix: string;
}

export function CoinbaseClientCfgFromJSON(json: any): CoinbaseClientCfg {
  return CoinbaseClientCfgFromJSONTyped(json, false);
}

export function CoinbaseClientCfgFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CoinbaseClientCfg {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    trackingPrefix: json["trackingPrefix"],
  };
}

export function CoinbaseClientCfgToJSONRecursive(
  value?: CoinbaseClientCfg | null,
  ignoreParent = false
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }

  return {
    trackingPrefix: value.trackingPrefix,
  };
}

export function CoinbaseClientCfgToJSON(value?: CoinbaseClientCfg | null): any {
  return CoinbaseClientCfgToJSONRecursive(value, false);
}
