/* tslint:disable */
/* eslint-disable */
/**
 * brokerize
 * The brokerize API allows clients to implement multi-brokerage with a unified interface. For more information, visit brokerize.com
 *
 * The version of the OpenAPI document: 0.0.1-preview
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ConfirmOAuthParams
 */
export interface ConfirmOAuthParams {
  /**
   *
   * @type {string}
   * @memberof ConfirmOAuthParams
   */
  code: string;
  /**
   *
   * @type {string}
   * @memberof ConfirmOAuthParams
   */
  ticketId: string;
}

export function ConfirmOAuthParamsFromJSON(json: any): ConfirmOAuthParams {
  return ConfirmOAuthParamsFromJSONTyped(json, false);
}

export function ConfirmOAuthParamsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ConfirmOAuthParams {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    code: json["code"],
    ticketId: json["ticketId"],
  };
}

export function ConfirmOAuthParamsToJSONRecursive(
  value?: ConfirmOAuthParams | null,
  ignoreParent = false
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }

  return {
    code: value.code,
    ticketId: value.ticketId,
  };
}

export function ConfirmOAuthParamsToJSON(
  value?: ConfirmOAuthParams | null
): any {
  return ConfirmOAuthParamsToJSONRecursive(value, false);
}
