/* tslint:disable */
/* eslint-disable */
/**
 * brokerize
 * The brokerize API allows clients to implement multi-brokerage with a unified interface. For more information, visit brokerize.com
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CreateRecoveryPhraseParams
 */
export interface CreateRecoveryPhraseParams {
  /**
   * A name for the RecoveryPhrase. Must be unique for the user so that they can identify it in the list
   * of RecoveryPhrases.
   * @type {string}
   * @memberof CreateRecoveryPhraseParams
   */
  name: string;
}

export function CreateRecoveryPhraseParamsFromJSON(
  json: any
): CreateRecoveryPhraseParams {
  return CreateRecoveryPhraseParamsFromJSONTyped(json, false);
}

export function CreateRecoveryPhraseParamsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CreateRecoveryPhraseParams {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: json["name"],
  };
}

export function CreateRecoveryPhraseParamsToJSONRecursive(
  value?: CreateRecoveryPhraseParams | null,
  ignoreParent = false
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }

  return {
    name: value.name,
  };
}

export function CreateRecoveryPhraseParamsToJSON(
  value?: CreateRecoveryPhraseParams | null
): any {
  return CreateRecoveryPhraseParamsToJSONRecursive(value, false);
}
