/* tslint:disable */
/* eslint-disable */
/**
 * brokerize
 * The brokerize API allows clients to implement multi-brokerage with a unified interface. For more information, visit brokerize.com
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CreateRecoveryPhraseResult
 */
export interface CreateRecoveryPhraseResult {
  /**
   *
   * @type {string}
   * @memberof CreateRecoveryPhraseResult
   */
  recoveryPhrase: string;
}

export function CreateRecoveryPhraseResultFromJSON(
  json: any
): CreateRecoveryPhraseResult {
  return CreateRecoveryPhraseResultFromJSONTyped(json, false);
}

export function CreateRecoveryPhraseResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CreateRecoveryPhraseResult {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    recoveryPhrase: json["recoveryPhrase"],
  };
}

export function CreateRecoveryPhraseResultToJSONRecursive(
  value?: CreateRecoveryPhraseResult | null,
  ignoreParent = false
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }

  return {
    recoveryPhrase: value.recoveryPhrase,
  };
}

export function CreateRecoveryPhraseResultToJSON(
  value?: CreateRecoveryPhraseResult | null
): any {
  return CreateRecoveryPhraseResultToJSONRecursive(value, false);
}
