/* tslint:disable */
/* eslint-disable */
/**
 * brokerize
 * The brokerize API allows clients to implement multi-brokerage with a unified interface. For more information, visit brokerize.com
 *
 * The version of the OpenAPI document: 0.0.1-preview
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    OrderValidity,
    OrderValidityFromJSON,
    OrderValidityFromJSONTyped,
    OrderValidityToJSON,
} from './OrderValidity';

/**
 * 
 * @export
 * @interface DefaultOrderValidityByOrderModel
 */
export interface DefaultOrderValidityByOrderModel {
    /**
     * 
     * @type {OrderValidity}
     * @memberof DefaultOrderValidityByOrderModel
     */
    quote?: OrderValidity;
    /**
     * 
     * @type {OrderValidity}
     * @memberof DefaultOrderValidityByOrderModel
     */
    fraction?: OrderValidity;
    /**
     * 
     * @type {OrderValidity}
     * @memberof DefaultOrderValidityByOrderModel
     */
    savingsPlan?: OrderValidity;
    /**
     * 
     * @type {OrderValidity}
     * @memberof DefaultOrderValidityByOrderModel
     */
    market?: OrderValidity;
    /**
     * 
     * @type {OrderValidity}
     * @memberof DefaultOrderValidityByOrderModel
     */
    limit?: OrderValidity;
    /**
     * 
     * @type {OrderValidity}
     * @memberof DefaultOrderValidityByOrderModel
     */
    stopMarket?: OrderValidity;
    /**
     * 
     * @type {OrderValidity}
     * @memberof DefaultOrderValidityByOrderModel
     */
    stopLimit?: OrderValidity;
    /**
     * 
     * @type {OrderValidity}
     * @memberof DefaultOrderValidityByOrderModel
     */
    trailingStopMarket?: OrderValidity;
    /**
     * 
     * @type {OrderValidity}
     * @memberof DefaultOrderValidityByOrderModel
     */
    trailingStopLimit?: OrderValidity;
    /**
     * 
     * @type {OrderValidity}
     * @memberof DefaultOrderValidityByOrderModel
     */
    ocoStopMarket?: OrderValidity;
    /**
     * 
     * @type {OrderValidity}
     * @memberof DefaultOrderValidityByOrderModel
     */
    ocoStopLimit?: OrderValidity;
}

export function DefaultOrderValidityByOrderModelFromJSON(json: any): DefaultOrderValidityByOrderModel {
    return DefaultOrderValidityByOrderModelFromJSONTyped(json, false);
}

export function DefaultOrderValidityByOrderModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): DefaultOrderValidityByOrderModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'quote': !exists(json, 'quote') ? undefined : OrderValidityFromJSON(json['quote']),
        'fraction': !exists(json, 'fraction') ? undefined : OrderValidityFromJSON(json['fraction']),
        'savingsPlan': !exists(json, 'savingsPlan') ? undefined : OrderValidityFromJSON(json['savingsPlan']),
        'market': !exists(json, 'market') ? undefined : OrderValidityFromJSON(json['market']),
        'limit': !exists(json, 'limit') ? undefined : OrderValidityFromJSON(json['limit']),
        'stopMarket': !exists(json, 'stopMarket') ? undefined : OrderValidityFromJSON(json['stopMarket']),
        'stopLimit': !exists(json, 'stopLimit') ? undefined : OrderValidityFromJSON(json['stopLimit']),
        'trailingStopMarket': !exists(json, 'trailingStopMarket') ? undefined : OrderValidityFromJSON(json['trailingStopMarket']),
        'trailingStopLimit': !exists(json, 'trailingStopLimit') ? undefined : OrderValidityFromJSON(json['trailingStopLimit']),
        'ocoStopMarket': !exists(json, 'ocoStopMarket') ? undefined : OrderValidityFromJSON(json['ocoStopMarket']),
        'ocoStopLimit': !exists(json, 'ocoStopLimit') ? undefined : OrderValidityFromJSON(json['ocoStopLimit']),
    };
}

export function DefaultOrderValidityByOrderModelToJSONRecursive(value?: DefaultOrderValidityByOrderModel | null, ignoreParent = false): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    return {
        


        'quote': OrderValidityToJSON(value.quote),
        'fraction': OrderValidityToJSON(value.fraction),
        'savingsPlan': OrderValidityToJSON(value.savingsPlan),
        'market': OrderValidityToJSON(value.market),
        'limit': OrderValidityToJSON(value.limit),
        'stopMarket': OrderValidityToJSON(value.stopMarket),
        'stopLimit': OrderValidityToJSON(value.stopLimit),
        'trailingStopMarket': OrderValidityToJSON(value.trailingStopMarket),
        'trailingStopLimit': OrderValidityToJSON(value.trailingStopLimit),
        'ocoStopMarket': OrderValidityToJSON(value.ocoStopMarket),
        'ocoStopLimit': OrderValidityToJSON(value.ocoStopLimit),
    };
}

export function DefaultOrderValidityByOrderModelToJSON(value?: DefaultOrderValidityByOrderModel | null): any {
    return DefaultOrderValidityByOrderModelToJSONRecursive(value, false);
}
