/* tslint:disable */
/* eslint-disable */
/**
 * brokerize
 * The brokerize API allows clients to implement multi-brokerage with a unified interface. For more information, visit brokerize.com
 *
 * The version of the OpenAPI document: 0.0.1-preview
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface EnableSessionTanParamsDecoupledAllOf
 */
export interface EnableSessionTanParamsDecoupledAllOf {
  /**
   *
   * @type {string}
   * @memberof EnableSessionTanParamsDecoupledAllOf
   */
  kind?: EnableSessionTanParamsDecoupledAllOfKindEnum;
}

/**
 * @export
 */
export const EnableSessionTanParamsDecoupledAllOfKindEnum = {
  Decoupled: "decoupled",
} as const;
export type EnableSessionTanParamsDecoupledAllOfKindEnum =
  (typeof EnableSessionTanParamsDecoupledAllOfKindEnum)[keyof typeof EnableSessionTanParamsDecoupledAllOfKindEnum];

export function EnableSessionTanParamsDecoupledAllOfFromJSON(
  json: any
): EnableSessionTanParamsDecoupledAllOf {
  return EnableSessionTanParamsDecoupledAllOfFromJSONTyped(json, false);
}

export function EnableSessionTanParamsDecoupledAllOfFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EnableSessionTanParamsDecoupledAllOf {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    kind: !exists(json, "kind") ? undefined : json["kind"],
  };
}

export function EnableSessionTanParamsDecoupledAllOfToJSONRecursive(
  value?: EnableSessionTanParamsDecoupledAllOf | null,
  ignoreParent = false
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }

  return {
    kind: value.kind,
  };
}

export function EnableSessionTanParamsDecoupledAllOfToJSON(
  value?: EnableSessionTanParamsDecoupledAllOf | null
): any {
  return EnableSessionTanParamsDecoupledAllOfToJSONRecursive(value, false);
}
