/* tslint:disable */
/* eslint-disable */
/**
 * brokerize
 * The brokerize API allows clients to implement multi-brokerage with a unified interface. For more information, visit brokerize.com
 *
 * The version of the OpenAPI document: 0.0.1-preview
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import {
  OrderChanges,
  OrderChangesFromJSON,
  OrderChangesFromJSONTyped,
  OrderChangesToJSON,
} from "./OrderChanges";

/**
 *
 * @export
 * @interface EstimateChangeOrderCostsParams
 */
export interface EstimateChangeOrderCostsParams {
  /**
   *
   * @type {OrderChanges}
   * @memberof EstimateChangeOrderCostsParams
   */
  changes: OrderChanges;
}

export function EstimateChangeOrderCostsParamsFromJSON(
  json: any
): EstimateChangeOrderCostsParams {
  return EstimateChangeOrderCostsParamsFromJSONTyped(json, false);
}

export function EstimateChangeOrderCostsParamsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EstimateChangeOrderCostsParams {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    changes: OrderChangesFromJSON(json["changes"]),
  };
}

export function EstimateChangeOrderCostsParamsToJSONRecursive(
  value?: EstimateChangeOrderCostsParams | null,
  ignoreParent = false
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }

  return {
    changes: OrderChangesToJSON(value.changes),
  };
}

export function EstimateChangeOrderCostsParamsToJSON(
  value?: EstimateChangeOrderCostsParams | null
): any {
  return EstimateChangeOrderCostsParamsToJSONRecursive(value, false);
}
