/* tslint:disable */
/* eslint-disable */
/**
 * brokerize
 * The brokerize API allows clients to implement multi-brokerage with a unified interface. For more information, visit brokerize.com
 *
 * The version of the OpenAPI document: 0.0.1-preview
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ExchangeMeta
 */
export interface ExchangeMeta {
  /**
   *
   * @type {number}
   * @memberof ExchangeMeta
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof ExchangeMeta
   */
  name: string;
}

export function ExchangeMetaFromJSON(json: any): ExchangeMeta {
  return ExchangeMetaFromJSONTyped(json, false);
}

export function ExchangeMetaFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ExchangeMeta {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    name: json["name"],
  };
}

export function ExchangeMetaToJSONRecursive(
  value?: ExchangeMeta | null,
  ignoreParent = false
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }

  return {
    id: value.id,
    name: value.name,
  };
}

export function ExchangeMetaToJSON(value?: ExchangeMeta | null): any {
  return ExchangeMetaToJSONRecursive(value, false);
}
