/* tslint:disable */
/* eslint-disable */
/**
 * brokerize
 * The brokerize API allows clients to implement multi-brokerage with a unified interface. For more information, visit brokerize.com
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface GenericTableRowValueDatetimeAllOf
 */
export interface GenericTableRowValueDatetimeAllOf {
  /**
   *
   * @type {string}
   * @memberof GenericTableRowValueDatetimeAllOf
   */
  type?: GenericTableRowValueDatetimeAllOfTypeEnum;
}

/**
 * @export
 */
export const GenericTableRowValueDatetimeAllOfTypeEnum = {
  Datetime: "datetime",
} as const;
export type GenericTableRowValueDatetimeAllOfTypeEnum =
  (typeof GenericTableRowValueDatetimeAllOfTypeEnum)[keyof typeof GenericTableRowValueDatetimeAllOfTypeEnum];

export function GenericTableRowValueDatetimeAllOfFromJSON(
  json: any
): GenericTableRowValueDatetimeAllOf {
  return GenericTableRowValueDatetimeAllOfFromJSONTyped(json, false);
}

export function GenericTableRowValueDatetimeAllOfFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): GenericTableRowValueDatetimeAllOf {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    type: !exists(json, "type") ? undefined : json["type"],
  };
}

export function GenericTableRowValueDatetimeAllOfToJSONRecursive(
  value?: GenericTableRowValueDatetimeAllOf | null,
  ignoreParent = false
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }

  return {
    type: value.type,
  };
}

export function GenericTableRowValueDatetimeAllOfToJSON(
  value?: GenericTableRowValueDatetimeAllOf | null
): any {
  return GenericTableRowValueDatetimeAllOfToJSONRecursive(value, false);
}
