/* tslint:disable */
/* eslint-disable */
/**
 * brokerize
 * The brokerize API allows clients to implement multi-brokerage with a unified interface. For more information, visit brokerize.com
 *
 * The version of the OpenAPI document: 0.0.1-preview
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GenericTableRowEntryAllOf
 */
export interface GenericTableRowEntryAllOf {
    /**
     * 
     * @type {string}
     * @memberof GenericTableRowEntryAllOf
     */
    type?: GenericTableRowEntryAllOfTypeEnum;
}


/**
 * @export
 */
export const GenericTableRowEntryAllOfTypeEnum = {
    Entry: 'entry'
} as const;
export type GenericTableRowEntryAllOfTypeEnum = typeof GenericTableRowEntryAllOfTypeEnum[keyof typeof GenericTableRowEntryAllOfTypeEnum];


export function GenericTableRowEntryAllOfFromJSON(json: any): GenericTableRowEntryAllOf {
    return GenericTableRowEntryAllOfFromJSONTyped(json, false);
}

export function GenericTableRowEntryAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenericTableRowEntryAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': !exists(json, 'type') ? undefined : json['type'],
    };
}

export function GenericTableRowEntryAllOfToJSONRecursive(value?: GenericTableRowEntryAllOf | null, ignoreParent = false): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    return {
        


        'type': value.type,
    };
}

export function GenericTableRowEntryAllOfToJSON(value?: GenericTableRowEntryAllOf | null): any {
    return GenericTableRowEntryAllOfToJSONRecursive(value, false);
}
