/* tslint:disable */
/* eslint-disable */
/**
 * brokerize
 * The brokerize API allows clients to implement multi-brokerage with a unified interface. For more information, visit brokerize.com
 *
 * The version of the OpenAPI document: 1.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface GenericTableRowValueTextSpecifics
 */
export interface GenericTableRowValueTextSpecifics {
  /**
   *
   * @type {string}
   * @memberof GenericTableRowValueTextSpecifics
   */
  value?: string;
}

export function GenericTableRowValueTextSpecificsFromJSON(
  json: any
): GenericTableRowValueTextSpecifics {
  return GenericTableRowValueTextSpecificsFromJSONTyped(json, false);
}

export function GenericTableRowValueTextSpecificsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): GenericTableRowValueTextSpecifics {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    value: !exists(json, "value") ? undefined : json["value"],
  };
}

export function GenericTableRowValueTextSpecificsToJSONRecursive(
  value?: GenericTableRowValueTextSpecifics | null,
  ignoreParent = false
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }

  return {
    value: value.value,
  };
}

export function GenericTableRowValueTextSpecificsToJSON(
  value?: GenericTableRowValueTextSpecifics | null
): any {
  return GenericTableRowValueTextSpecificsToJSONRecursive(value, false);
}
