/* tslint:disable */
/* eslint-disable */
/**
 * brokerize
 * The brokerize API allows clients to implement multi-brokerage with a unified interface. For more information, visit brokerize.com
 *
 * The version of the OpenAPI document: 0.0.1-preview
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface InboxOrderParams
 */
export interface InboxOrderParams {
  /**
   *
   * @type {string}
   * @memberof InboxOrderParams
   */
  description?: string;
  /**
   *
   * @type {any}
   * @memberof InboxOrderParams
   */
  orderData: any | null;
}

export function InboxOrderParamsFromJSON(json: any): InboxOrderParams {
  return InboxOrderParamsFromJSONTyped(json, false);
}

export function InboxOrderParamsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): InboxOrderParams {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    description: !exists(json, "description") ? undefined : json["description"],
    orderData: json["orderData"],
  };
}

export function InboxOrderParamsToJSONRecursive(
  value?: InboxOrderParams | null,
  ignoreParent = false
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }

  return {
    description: value.description,
    orderData: value.orderData,
  };
}

export function InboxOrderParamsToJSON(value?: InboxOrderParams | null): any {
  return InboxOrderParamsToJSONRecursive(value, false);
}
