/* tslint:disable */
/* eslint-disable */
/**
 * brokerize
 * The brokerize API allows clients to implement multi-brokerage with a unified interface. For more information, visit brokerize.com
 *
 * The version of the OpenAPI document: 0.0.1-preview
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 * Inbox orders are orders saved into the inbox of the user, to be reviewed and possibly executed at a later time.
 * @export
 * @interface InboxOrder
 */
export interface InboxOrder {
  /**
   * The date when this inbox order was created
   * @type {Date}
   * @memberof InboxOrder
   */
  createdAt: Date;
  /**
   * Information about the connected order.
   * @type {string}
   * @memberof InboxOrder
   */
  description: string;
  /**
   *
   * @type {string}
   * @memberof InboxOrder
   */
  id: string;
  /**
   * Whether the inbox order is still active. Executing or dismissing the trade turns the flag to `true`
   * @type {boolean}
   * @memberof InboxOrder
   */
  inactive: boolean;
  /**
   * The data of the inbox order to be executed
   * @type {any}
   * @memberof InboxOrder
   */
  orderData: any | null;
  /**
   * If the inbox order is executed, the returned orderId is saved in here
   * @type {number}
   * @memberof InboxOrder
   */
  orderId: number;
  /**
   *
   * @type {number}
   * @memberof InboxOrder
   */
  userId: number;
}

export function InboxOrderFromJSON(json: any): InboxOrder {
  return InboxOrderFromJSONTyped(json, false);
}

export function InboxOrderFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): InboxOrder {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    createdAt: new Date(json["createdAt"]),
    description: json["description"],
    id: json["id"],
    inactive: json["inactive"],
    orderData: json["orderData"],
    orderId: json["orderId"],
    userId: json["userId"],
  };
}

export function InboxOrderToJSONRecursive(
  value?: InboxOrder | null,
  ignoreParent = false
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }

  return {
    createdAt: value.createdAt.toISOString(),
    description: value.description,
    id: value.id,
    inactive: value.inactive,
    orderData: value.orderData,
    orderId: value.orderId,
    userId: value.userId,
  };
}

export function InboxOrderToJSON(value?: InboxOrder | null): any {
  return InboxOrderToJSONRecursive(value, false);
}
