/* tslint:disable */
/* eslint-disable */
/**
 * brokerize
 * The brokerize API allows clients to implement multi-brokerage with a unified interface. For more information, visit brokerize.com
 *
 * The version of the OpenAPI document: 0.0.1-preview
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginResponseReadySpecifics
 */
export interface LoginResponseReadySpecifics {
    /**
     * 
     * @type {string}
     * @memberof LoginResponseReadySpecifics
     */
    sessionId?: string;
}

export function LoginResponseReadySpecificsFromJSON(json: any): LoginResponseReadySpecifics {
    return LoginResponseReadySpecificsFromJSONTyped(json, false);
}

export function LoginResponseReadySpecificsFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginResponseReadySpecifics {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'sessionId': !exists(json, 'sessionId') ? undefined : json['sessionId'],
    };
}

export function LoginResponseReadySpecificsToJSONRecursive(value?: LoginResponseReadySpecifics | null, ignoreParent = false): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    return {
        


        'sessionId': value.sessionId,
    };
}

export function LoginResponseReadySpecificsToJSON(value?: LoginResponseReadySpecifics | null): any {
    return LoginResponseReadySpecificsToJSONRecursive(value, false);
}
