/* tslint:disable */
/* eslint-disable */
/**
 * brokerize
 * The brokerize API allows clients to implement multi-brokerage with a unified interface. For more information, visit brokerize.com
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface OAuthLoginFormConfig
 */
export interface OAuthLoginFormConfig {
  /**
   *
   * @type {string}
   * @memberof OAuthLoginFormConfig
   */
  appName?: string;
  /**
   *
   * @type {string}
   * @memberof OAuthLoginFormConfig
   */
  logoUrlDark?: string;
  /**
   *
   * @type {string}
   * @memberof OAuthLoginFormConfig
   */
  logoUrlLight?: string;
  /**
   * How the browser is sent back to the `returnTo` URL after a successful broker login.
   *
   * `meta`, `js` and `link` render the interstitial callback screen and redirect from there (via a
   * meta refresh, via JavaScript, or by revealing a link the user clicks). `http` skips the screen
   * and answers the callback with a plain HTTP 302 instead.
   *
   * `http` only applies to `http`/`https` `returnTo` URLs. A `returnTo` in a custom app scheme
   * still gets the interstitial, because browsers handle a 302 into an app scheme inconsistently.
   *
   * Default is `meta`.
   * @type {string}
   * @memberof OAuthLoginFormConfig
   */
  redirectStyle?: OAuthLoginFormConfigRedirectStyleEnum;
  /**
   * Overrides `redirectStyle` for logins at bitpanda.
   * @type {string}
   * @memberof OAuthLoginFormConfig
   */
  redirectStyleBitpanda?: OAuthLoginFormConfigRedirectStyleBitpandaEnum;
}

/**
 * @export
 */
export const OAuthLoginFormConfigRedirectStyleEnum = {
  Meta: "meta",
  Js: "js",
  Link: "link",
  Http: "http",
} as const;
export type OAuthLoginFormConfigRedirectStyleEnum =
  (typeof OAuthLoginFormConfigRedirectStyleEnum)[keyof typeof OAuthLoginFormConfigRedirectStyleEnum];

/**
 * @export
 */
export const OAuthLoginFormConfigRedirectStyleBitpandaEnum = {
  Meta: "meta",
  Js: "js",
  Link: "link",
  Http: "http",
} as const;
export type OAuthLoginFormConfigRedirectStyleBitpandaEnum =
  (typeof OAuthLoginFormConfigRedirectStyleBitpandaEnum)[keyof typeof OAuthLoginFormConfigRedirectStyleBitpandaEnum];

export function OAuthLoginFormConfigFromJSON(json: any): OAuthLoginFormConfig {
  return OAuthLoginFormConfigFromJSONTyped(json, false);
}

export function OAuthLoginFormConfigFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): OAuthLoginFormConfig {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    appName: !exists(json, "appName") ? undefined : json["appName"],
    logoUrlDark: !exists(json, "logoUrlDark") ? undefined : json["logoUrlDark"],
    logoUrlLight: !exists(json, "logoUrlLight")
      ? undefined
      : json["logoUrlLight"],
    redirectStyle: !exists(json, "redirectStyle")
      ? undefined
      : json["redirectStyle"],
    redirectStyleBitpanda: !exists(json, "redirectStyleBitpanda")
      ? undefined
      : json["redirectStyleBitpanda"],
  };
}

export function OAuthLoginFormConfigToJSONRecursive(
  value?: OAuthLoginFormConfig | null,
  ignoreParent = false,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }

  return {
    appName: value.appName,
    logoUrlDark: value.logoUrlDark,
    logoUrlLight: value.logoUrlLight,
    redirectStyle: value.redirectStyle,
    redirectStyleBitpanda: value.redirectStyleBitpanda,
  };
}

export function OAuthLoginFormConfigToJSON(
  value?: OAuthLoginFormConfig | null,
): any {
  return OAuthLoginFormConfigToJSONRecursive(value, false);
}
