/* tslint:disable */
/* eslint-disable */
/**
 * brokerize
 * The brokerize API allows clients to implement multi-brokerage with a unified interface. For more information, visit brokerize.com
 *
 * The version of the OpenAPI document: 0.0.1-preview
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const OrderStatus = {
  Open: "open",
  Canceled: "canceled",
  Executed: "executed",
  OpenExecuted: "open_executed",
  CanceledExecuted: "canceled_executed",
} as const;
export type OrderStatus = (typeof OrderStatus)[keyof typeof OrderStatus];

export function OrderStatusFromJSON(json: any): OrderStatus {
  return OrderStatusFromJSONTyped(json, false);
}

export function OrderStatusFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): OrderStatus {
  return json as OrderStatus;
}

export function OrderStatusToJSON(value?: OrderStatus | null): any {
  return value as any;
}
