/* tslint:disable */
/* eslint-disable */
/**
 * brokerize
 * The brokerize API allows clients to implement multi-brokerage with a unified interface. For more information, visit brokerize.com
 *
 * The version of the OpenAPI document: 0.0.1-preview
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface PortfolioSyncInfoCompleteSpecifics
 */
export interface PortfolioSyncInfoCompleteSpecifics {
  /**
   *
   * @type {Date}
   * @memberof PortfolioSyncInfoCompleteSpecifics
   */
  lastSync?: Date;
}

export function PortfolioSyncInfoCompleteSpecificsFromJSON(
  json: any
): PortfolioSyncInfoCompleteSpecifics {
  return PortfolioSyncInfoCompleteSpecificsFromJSONTyped(json, false);
}

export function PortfolioSyncInfoCompleteSpecificsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PortfolioSyncInfoCompleteSpecifics {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    lastSync: !exists(json, "lastSync")
      ? undefined
      : new Date(json["lastSync"]),
  };
}

export function PortfolioSyncInfoCompleteSpecificsToJSONRecursive(
  value?: PortfolioSyncInfoCompleteSpecifics | null,
  ignoreParent = false
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }

  return {
    lastSync:
      value.lastSync === undefined ? undefined : value.lastSync.toISOString(),
  };
}

export function PortfolioSyncInfoCompleteSpecificsToJSON(
  value?: PortfolioSyncInfoCompleteSpecifics | null
): any {
  return PortfolioSyncInfoCompleteSpecificsToJSONRecursive(value, false);
}
