/* tslint:disable */
/* eslint-disable */
/**
 * brokerize
 * The brokerize API allows clients to implement multi-brokerage with a unified interface. For more information, visit brokerize.com
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface PrepareOAuthRedirectParams
 */
export interface PrepareOAuthRedirectParams {
  /**
   * Preferred appearance for login screens. Note that this can only be set explicitly for some selected brokers.
   * If the broker does not support it, this is silently ignored and the default broker appearance is used.
   * @type {string}
   * @memberof PrepareOAuthRedirectParams
   */
  appearance?: PrepareOAuthRedirectParamsAppearanceEnum;
  /**
   *
   * @type {string}
   * @memberof PrepareOAuthRedirectParams
   */
  brokerName: string;
  /**
   *
   * @type {string}
   * @memberof PrepareOAuthRedirectParams
   */
  env: string;
  /**
   *
   * @type {string}
   * @memberof PrepareOAuthRedirectParams
   */
  returnToUrl: string;
}

/**
 * @export
 */
export const PrepareOAuthRedirectParamsAppearanceEnum = {
  Light: "light",
  Dark: "dark",
} as const;
export type PrepareOAuthRedirectParamsAppearanceEnum =
  (typeof PrepareOAuthRedirectParamsAppearanceEnum)[keyof typeof PrepareOAuthRedirectParamsAppearanceEnum];

export function PrepareOAuthRedirectParamsFromJSON(
  json: any,
): PrepareOAuthRedirectParams {
  return PrepareOAuthRedirectParamsFromJSONTyped(json, false);
}

export function PrepareOAuthRedirectParamsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PrepareOAuthRedirectParams {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    appearance: !exists(json, "appearance") ? undefined : json["appearance"],
    brokerName: json["brokerName"],
    env: json["env"],
    returnToUrl: json["returnToUrl"],
  };
}

export function PrepareOAuthRedirectParamsToJSONRecursive(
  value?: PrepareOAuthRedirectParams | null,
  ignoreParent = false,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }

  return {
    appearance: value.appearance,
    brokerName: value.brokerName,
    env: value.env,
    returnToUrl: value.returnToUrl,
  };
}

export function PrepareOAuthRedirectParamsToJSON(
  value?: PrepareOAuthRedirectParams | null,
): any {
  return PrepareOAuthRedirectParamsToJSONRecursive(value, false);
}
