/* tslint:disable */
/* eslint-disable */
/**
 * brokerize
 * The brokerize API allows clients to implement multi-brokerage with a unified interface. For more information, visit brokerize.com
 *
 * The version of the OpenAPI document: 0.0.1-preview
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface SessionSyncInfoSyncedSpecifics
 */
export interface SessionSyncInfoSyncedSpecifics {
  /**
   *
   * @type {Date}
   * @memberof SessionSyncInfoSyncedSpecifics
   */
  lastSync?: Date;
}

export function SessionSyncInfoSyncedSpecificsFromJSON(
  json: any
): SessionSyncInfoSyncedSpecifics {
  return SessionSyncInfoSyncedSpecificsFromJSONTyped(json, false);
}

export function SessionSyncInfoSyncedSpecificsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SessionSyncInfoSyncedSpecifics {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    lastSync: !exists(json, "lastSync")
      ? undefined
      : new Date(json["lastSync"]),
  };
}

export function SessionSyncInfoSyncedSpecificsToJSONRecursive(
  value?: SessionSyncInfoSyncedSpecifics | null,
  ignoreParent = false
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }

  return {
    lastSync:
      value.lastSync === undefined ? undefined : value.lastSync.toISOString(),
  };
}

export function SessionSyncInfoSyncedSpecificsToJSON(
  value?: SessionSyncInfoSyncedSpecifics | null
): any {
  return SessionSyncInfoSyncedSpecificsToJSONRecursive(value, false);
}
