/* tslint:disable */
/* eslint-disable */
/**
 * brokerize
 * The brokerize API allows clients to implement multi-brokerage with a unified interface. For more information, visit brokerize.com
 *
 * The version of the OpenAPI document: 0.0.1-preview
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PortfolioSyncInfoErrorAllOf,
    PortfolioSyncInfoErrorAllOfFromJSON,
    PortfolioSyncInfoErrorAllOfFromJSONTyped,
    PortfolioSyncInfoErrorAllOfToJSON,
} from './PortfolioSyncInfoErrorAllOf';
import {
    SessionSyncInfoErrorSpecifics,
    SessionSyncInfoErrorSpecificsFromJSON,
    SessionSyncInfoErrorSpecificsFromJSONTyped,
    SessionSyncInfoErrorSpecificsToJSON,
} from './SessionSyncInfoErrorSpecifics';
import {
    SyncError,
    SyncErrorFromJSON,
    SyncErrorFromJSONTyped,
    SyncErrorToJSON,
} from './SyncError';

/**
 * 
 * @export
 * @interface SessionSyncInfoError
 */
export interface SessionSyncInfoError {
    /**
     * 
     * @type {string}
     * @memberof SessionSyncInfoError
     */
    status: SessionSyncInfoErrorStatusEnum;
    /**
     * 
     * @type {SyncError}
     * @memberof SessionSyncInfoError
     */
    error: SyncError;
}


/**
 * @export
 */
export const SessionSyncInfoErrorStatusEnum = {
    Error: 'ERROR'
} as const;
export type SessionSyncInfoErrorStatusEnum = typeof SessionSyncInfoErrorStatusEnum[keyof typeof SessionSyncInfoErrorStatusEnum];


export function SessionSyncInfoErrorFromJSON(json: any): SessionSyncInfoError {
    return SessionSyncInfoErrorFromJSONTyped(json, false);
}

export function SessionSyncInfoErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionSyncInfoError {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': json['status'],
        'error': SyncErrorFromJSON(json['error']),
    };
}

export function SessionSyncInfoErrorToJSONRecursive(value?: SessionSyncInfoError | null, ignoreParent = false): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    return {
        


        'status': value.status,
        'error': SyncErrorToJSON(value.error),
    };
}

export function SessionSyncInfoErrorToJSON(value?: SessionSyncInfoError | null): any {
    return SessionSyncInfoErrorToJSONRecursive(value, false);
}
