/* tslint:disable */
/* eslint-disable */
/**
 * brokerize
 * The brokerize API allows clients to implement multi-brokerage with a unified interface. For more information, visit brokerize.com
 *
 * The version of the OpenAPI document: 0.0.1-preview
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface SyncError
 */
export interface SyncError {
  /**
   *
   * @type {string}
   * @memberof SyncError
   */
  message: string;
  /**
   *
   * @type {Date}
   * @memberof SyncError
   */
  date: Date;
}

export function SyncErrorFromJSON(json: any): SyncError {
  return SyncErrorFromJSONTyped(json, false);
}

export function SyncErrorFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SyncError {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    message: json["message"],
    date: new Date(json["date"]),
  };
}

export function SyncErrorToJSONRecursive(
  value?: SyncError | null,
  ignoreParent = false
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }

  return {
    message: value.message,
    date: value.date.toISOString(),
  };
}

export function SyncErrorToJSON(value?: SyncError | null): any {
  return SyncErrorToJSONRecursive(value, false);
}
