/* tslint:disable */
/* eslint-disable */
/**
 * brokerize
 * The brokerize API allows clients to implement multi-brokerage with a unified interface. For more information, visit brokerize.com
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface SyncHintAssumeOrderExecutedSpecifics
 */
export interface SyncHintAssumeOrderExecutedSpecifics {
  /**
   *
   * @type {string}
   * @memberof SyncHintAssumeOrderExecutedSpecifics
   */
  orderId?: string;
}

export function SyncHintAssumeOrderExecutedSpecificsFromJSON(
  json: any,
): SyncHintAssumeOrderExecutedSpecifics {
  return SyncHintAssumeOrderExecutedSpecificsFromJSONTyped(json, false);
}

export function SyncHintAssumeOrderExecutedSpecificsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SyncHintAssumeOrderExecutedSpecifics {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    orderId: !exists(json, "orderId") ? undefined : json["orderId"],
  };
}

export function SyncHintAssumeOrderExecutedSpecificsToJSONRecursive(
  value?: SyncHintAssumeOrderExecutedSpecifics | null,
  ignoreParent = false,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }

  return {
    orderId: value.orderId,
  };
}

export function SyncHintAssumeOrderExecutedSpecificsToJSON(
  value?: SyncHintAssumeOrderExecutedSpecifics | null,
): any {
  return SyncHintAssumeOrderExecutedSpecificsToJSONRecursive(value, false);
}
