/* tslint:disable */
/* eslint-disable */
/**
 * brokerize
 * The brokerize API allows clients to implement multi-brokerage with a unified interface. For more information, visit brokerize.com
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface SyncHintReloadOrderHistoryAllOf
 */
export interface SyncHintReloadOrderHistoryAllOf {
  /**
   *
   * @type {string}
   * @memberof SyncHintReloadOrderHistoryAllOf
   */
  type?: SyncHintReloadOrderHistoryAllOfTypeEnum;
}

/**
 * @export
 */
export const SyncHintReloadOrderHistoryAllOfTypeEnum = {
  ReloadOrderHistory: "ReloadOrderHistory",
} as const;
export type SyncHintReloadOrderHistoryAllOfTypeEnum =
  (typeof SyncHintReloadOrderHistoryAllOfTypeEnum)[keyof typeof SyncHintReloadOrderHistoryAllOfTypeEnum];

export function SyncHintReloadOrderHistoryAllOfFromJSON(
  json: any,
): SyncHintReloadOrderHistoryAllOf {
  return SyncHintReloadOrderHistoryAllOfFromJSONTyped(json, false);
}

export function SyncHintReloadOrderHistoryAllOfFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SyncHintReloadOrderHistoryAllOf {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    type: !exists(json, "type") ? undefined : json["type"],
  };
}

export function SyncHintReloadOrderHistoryAllOfToJSONRecursive(
  value?: SyncHintReloadOrderHistoryAllOf | null,
  ignoreParent = false,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }

  return {
    type: value.type,
  };
}

export function SyncHintReloadOrderHistoryAllOfToJSON(
  value?: SyncHintReloadOrderHistoryAllOf | null,
): any {
  return SyncHintReloadOrderHistoryAllOfToJSONRecursive(value, false);
}
