/* tslint:disable */
/* eslint-disable */
/**
 * brokerize
 * The brokerize API allows clients to implement multi-brokerage with a unified interface. For more information, visit brokerize.com
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface SyncHintManualReloadAllOf
 */
export interface SyncHintManualReloadAllOf {
  /**
   *
   * @type {string}
   * @memberof SyncHintManualReloadAllOf
   */
  type?: SyncHintManualReloadAllOfTypeEnum;
}

/**
 * @export
 */
export const SyncHintManualReloadAllOfTypeEnum = {
  ManualReload: "ManualReload",
} as const;
export type SyncHintManualReloadAllOfTypeEnum =
  (typeof SyncHintManualReloadAllOfTypeEnum)[keyof typeof SyncHintManualReloadAllOfTypeEnum];

export function SyncHintManualReloadAllOfFromJSON(
  json: any,
): SyncHintManualReloadAllOf {
  return SyncHintManualReloadAllOfFromJSONTyped(json, false);
}

export function SyncHintManualReloadAllOfFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SyncHintManualReloadAllOf {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    type: !exists(json, "type") ? undefined : json["type"],
  };
}

export function SyncHintManualReloadAllOfToJSONRecursive(
  value?: SyncHintManualReloadAllOf | null,
  ignoreParent = false,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }

  return {
    type: value.type,
  };
}

export function SyncHintManualReloadAllOfToJSON(
  value?: SyncHintManualReloadAllOf | null,
): any {
  return SyncHintManualReloadAllOfToJSONRecursive(value, false);
}
