/* tslint:disable */
/* eslint-disable */
/**
 * brokerize
 * The brokerize API allows clients to implement multi-brokerage with a unified interface. For more information, visit brokerize.com
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface TradeWarning
 */
export interface TradeWarning {
  /**
   *
   * @type {string}
   * @memberof TradeWarning
   */
  message: string;
}

export function TradeWarningFromJSON(json: any): TradeWarning {
  return TradeWarningFromJSONTyped(json, false);
}

export function TradeWarningFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): TradeWarning {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    message: json["message"],
  };
}

export function TradeWarningToJSONRecursive(
  value?: TradeWarning | null,
  ignoreParent = false
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }

  return {
    message: value.message,
  };
}

export function TradeWarningToJSON(value?: TradeWarning | null): any {
  return TradeWarningToJSONRecursive(value, false);
}
