name: Lint

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: ['lts/*']

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Cache npm modules
              uses: actions/cache@v3
              with:
                  path: ~/.npm-store
                  key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-

            - name: Install dependencies
              uses: actions/setup-node@v3
              with:
                  node-version-file: '.nvmrc'

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm ci
            - run: npm run lint
